-- MySQL Script generated by MySQL Workbench
-- Thu May 14 08:50:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cube_comp_prediction
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cube_comp_prediction` ;

-- -----------------------------------------------------
-- Schema cube_comp_prediction
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cube_comp_prediction` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cube_comp_prediction` ;

-- -----------------------------------------------------
-- Table `cube_comp_prediction`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cube_comp_prediction`.`users` ;

CREATE TABLE IF NOT EXISTS `cube_comp_prediction`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `hashed_password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cube_comp_prediction`.`instances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cube_comp_prediction`.`instances` ;

CREATE TABLE IF NOT EXISTS `cube_comp_prediction`.`instances` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `owned_by` VARCHAR(36) NOT NULL,
  `data` LONGTEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `owned_by_idx` (`owned_by` ASC) VISIBLE,
  CONSTRAINT `user_instance`
    FOREIGN KEY (`owned_by`)
    REFERENCES `cube_comp_prediction`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cube_comp_prediction`.`solutions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cube_comp_prediction`.`solutions` ;

CREATE TABLE IF NOT EXISTS `cube_comp_prediction`.`solutions` (
  `id` VARCHAR(36) NOT NULL,
  `instance_id` VARCHAR(36) NOT NULL,
  `data` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `deleted_at` TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `instance_solution_idx` (`instance_id` ASC) VISIBLE,
  CONSTRAINT `instance_solution`
    FOREIGN KEY (`instance_id`)
    REFERENCES `cube_comp_prediction`.`instances` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;