-- MySQL Script generated by MySQL Workbench
-- Thu May 14 08:50:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vncpickems
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vncpickems` ;

-- -----------------------------------------------------
-- Schema vncpickems
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vncpickems` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vncpickems` ;

-- -----------------------------------------------------
-- Table `vncpickems`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncpickems`.`admins` ;

CREATE TABLE IF NOT EXISTS `vncpickems`.`admins` (
  `username` VARCHAR(45) NOT NULL,
  `hashed_password` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncpickems`.`prediction_games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncpickems`.`prediction_games` ;

CREATE TABLE IF NOT EXISTS `vncpickems`.`prediction_games` (
  `competition_id` VARCHAR(100) NOT NULL,
  `published` TINYINT NOT NULL DEFAULT '0',
  `prediction_open` TIMESTAMP(6) NOT NULL,
  `prediction_close` TIMESTAMP(6) NOT NULL,
  `competition_start_date` DATE NOT NULL,
  `competition_end_date` DATE NOT NULL,
  `competition_registration_open` TIMESTAMP(6) NOT NULL,
  `competition_registration_close` TIMESTAMP(6) NOT NULL,
  `competition_country_iso2` VARCHAR(2) NOT NULL,
  `competition_event_ids` VARCHAR(100),
  `competition_psych_sheets` LONGTEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`competition_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncpickems`.`participants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncpickems`.`participants` ;

CREATE TABLE IF NOT EXISTS `vncpickems`.`participants` (
  `email` VARCHAR(100) NOT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  `facebook_url` VARCHAR(255) NULL DEFAULT NULL,
  `participates_in` VARCHAR(100) NOT NULL,
  `podium_prediction` LONGTEXT NULL DEFAULT NULL,
  `additional_prediction_number_of_nr` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `additional_prediction_avg_to_qualify_for_333_final` INT UNSIGNED NOT NULL DEFAULT 1000,
  `additional_prediction_avg_to_win_333_final` INT UNSIGNED NOT NULL DEFAULT 1000,
  `created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`email`, `participates_in`),
  INDEX `participates_in_idx` (`participates_in` ASC) VISIBLE,
  CONSTRAINT `prediction_participant`
    FOREIGN KEY (`participates_in`)
    REFERENCES `vncpickems`.`prediction_games` (`competition_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncpickems`.`competition_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncpickems`.`competition_results` ;

CREATE TABLE IF NOT EXISTS `vncpickems`.`competition_results` (
  `competition_id` VARCHAR(100) NOT NULL,
  `podium` LONGTEXT NULL DEFAULT NULL,
  `additional_result_number_of_nr` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `additional_result_avg_to_qualify_for_333_final` INT UNSIGNED NOT NULL DEFAULT 1000,
  `additional_result_avg_to_win_333_final` INT UNSIGNED NOT NULL DEFAULT 1000,
  `created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`competition_id`),
  CONSTRAINT `results_of_competition`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncpickems`.`prediction_games` (`competition_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;